name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libdbus
        run: |
          apt update
          apt install -y libdbus-1-dev pkg-config libudev-dev

      - name: Build and release
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/qmk-nowplaying
