name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pre-requisites
        run: |
          sudo apt update
          sudo apt install -y libdbus-1-dev pkg-config libudev-dev

      - name: Build imagemagick
        run: |
          git clone https://github.com/ImageMagick/ImageMagick.git ImageMagick-7.1.0 \
           && cd ImageMagick-7.1.0
           && ./configure --with-magick-plus-plus=no --with-perl=no \
           && make \
           && sudo make install \

      - name: Build and release
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/qmk-nowplaying
