name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pre-requisites
        run: |
          sudo apt update
          sudo apt install -y libdbus-1-dev pkg-config libudev-dev

      - name: Build imagemagick
        env:
          MAGICK_VERSION: 7.1
        run: |
          curl https://download.imagemagick.org/ImageMagick/download/ImageMagick.tar.gz | tar xz \
          cd ImageMagick-${MAGICK_VERSION}* \
          ./configure --with-magick-plus-plus=no --with-perl=no \
          make \
          make install \
          cd .. \
          rm -r ImageMagick-${MAGICK_VERSION}*



      - name: Build and release
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/qmk-nowplaying
